### ISSUE TITLE
How to check the edtion of Windows Key 

### ISSUE THREAD

**Issue by r31urn** [Superfly-Inc/ShowKeyPlus#12]
How to check with the product key for its edition?

Enlighten me. Any powershell commands?

pidgenx.dll winsxs .xaml lic files???
 
Help 👍

**Comment by Superfly-Inc** [comment]
Are you asking how ShowKeyPlus checks the edition or are you looking for an alternative method?

**Comment by r31urn** [comment]
Thank you for the reply!!  👍 
I wanted to know both  
1)I see that Showkey plus checks the edition by creating a new pidgenx2.dll file  ?
>how does it do that?
reason behind it
2) any alternative way (Powershell, or .vbs) method 

Also how to find the windows 7 OEM marker in the OS (as far as i know i have tried to get the PK from REG and WMIC)?

**Comment by Superfly-Inc** [comment]
Pidgenx is used to decode the key - the out parameters contain the id's required to parse pkconfig in order to get the edition. I am not aware of an alternate method.

Windows 7 marker is stored in the registry key HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT
That is the **name** of the SLIC in the firmware and the **certificate** that needs to be installed. The key is generic and useless without the SLIC and certificate and no use trying to find it in the OS. 
Goolge Win 7 OEM SLP keys if you want it.

I'm closing this as it's not really an issue, but thanks for your input.
