### ISSUE TITLE
Grammatical error in program

### ISSUE THREAD

**Issue by Dyras** [Superfly-Inc/ShowKeyPlus#24]
Greeting. It says "it's edition" when it should say "its edition". 

![bild](https://user-images.githubusercontent.com/12563436/65545019-d48f1e80-df14-11e9-8d75-99b3a238aa8b.png)

Cheers for a great program!

**Comment by Superfly-Inc** [comment]
Thanx @Dyras 

Yep, this issue and host of others have been fixed since then in the latest releases. The legacy version has been untouched for 4 years now. 

In case you are wondering, it's (correct?... LOL) still here as it supports XP and other stuff (lean, less memory etc) 

Cheers and all the best
