### ISSUE TITLE
Multilanguage interface

### ISSUE THREAD

**Issue by bovirus** [Superfly-Inc/ShowKeyPlus#27]
@Superfly-Inc 

Thanks a lot for your program.
Could you please consider if you ccan enable multi-language GUI?.
I can help translating it in italian.

**Comment by Superfly-Inc** [comment]
Thanx for your feedback and offer. 

I will add a language resource to the project. I do get a lot of non-English feedback at the Store.

I will keep you posted when I have a Preview version available for testing.

**Comment by bovirus** [comment]
@Superfly-Inc 

Thanks for this news.
Please post when you will have a preview version that can be localized.
Thanks.

**Comment by Superfly-Inc** [comment]
@bovirus 

I uploaded a multi-lingual version - only supports English and Italian for now.

Please check the linguistics in the enclosed .xlf file and will appreciate you replying with the corrections (I resorted to Google translate as Microsoft's auto translate didn't work for me)
It can be edited with this tool https://developer.microsoft.com/en-us/windows/downloads/multilingual-app-toolkit/

BTW the huge size is due to it being a .Net Core 3.1 app. now (self contained includes the required runtimes for portability) Version 1.1.14.4300 is compiled with 64-bit .Net Core 3.1 runtime.

Thanx.

**Comment by bovirus** [comment]
Thanks for the new multilanguage version.

I will check ASAP.

Note: I'm the Italian translator for Multilangual App Toolkit by MS. :-)

**Comment by bovirus** [comment]
@Superfly-Inc 
[ShowKeyPlusPreview_it-IT.zip](https://github.com/Superfly-Inc/ShowKeyPlus/files/4499116/ShowKeyPlusPreview_it-IT.zip)

I revised the Italian language.
I attached the language to the post.
I believed that I can see the chanegs directly but it seems that your .exe didn't read external .lif file.

**Comment by Superfly-Inc** [comment]
@bovirus

Thanx, nice work! 

I have included your corrections in build 1.1.14.44000 - note this is the smaller exe without the embedded runtime - please install the appropiate runtime before testing. 
(I hope it compiled correctly as I note it's even smaller that the Framework version.)

Regarding on-the-fly language changes, I'm not aware of that - I'm not a huge fan of external ini file type configs. This uses an it-IT folder with a compiled language dll - much like Windows' MUI files I guess.

**Comment by bovirus** [comment]
@Superfly-Inc 

Thanks for the new version.
I will test it.
Thanks.
