### ISSUE TITLE
The key is different in "Update and Security"?

### ISSUE THREAD

**Issue by vinixwu** [Superfly-Inc/ShowKeyPlus#4]
ShowKeyPlus displayed the last 5 digit as "6MT6Y" which is the same in all PCs after free OS upgrade, but I see "8HR36" in Update and Security > Activation.

So... is it possible for ShowKeyPlus to find the real key?

**Comment by Palanthis** [comment]
I can verify that on my Windows 10 PC (A Dell that came with Win 10 Home, but for which I purchased a full retail key for Win 10 Pro) ShowKey is correctly displaying both the original embedded key as well as the CORRECT key that Windows 10 Pro was installed with. Update and security for me also shows a nonsensical last 5, which doesn't match either my original key or my upgrade key. If I had to guess, it's Microsoft obfuscating it to cut down on piracy attempts.

**Comment by vinixwu** [comment]
It seems that no key is stored when I upgraded from old Windows version. I thought the 6MT6Y key is used as a install key ONLY and it depends on hardware record at servers of Microsoft for activation. I think ShowKeyPlus should show a warning sign to remind users about these install-only keys because using them on other computers will not activate.

**Comment by Superfly-Inc** [comment]
Thanx for the feedback. I'm not sure where "Update and Security" is getting that key from, however, I have noticed that since build 1607 there are additional registry product key fields. I haven't noticed this before, TBH, but will try to replicate and check where it's coming from.
Good point about alerting of default keys - in the meantimem check the PID - if that has zeros _after_ the first 4 digits, that indicates a generic key.
