### ISSUE TITLE
.Net Core based version ?

### ISSUE THREAD

**Issue by spinalgr1990** [Superfly-Inc/ShowKeyPlus#45]
How about to migrate to a .Net Core based version ?

**Comment by Superfly-Inc** [comment]
We had one before  - see the Preview change log

Gave up on it as this is Windows only and wanted the install to be seamless for everyone - I may go that that way with the next release though incl. WinUI 3 etc as there is not much happening otherwise  i.e no Win 11 keys and digital licences being encrypted. (PS: or shall I say I have not yet been able to decrypt the digital licence)

Cheers

**Comment by Superfly-Inc** [comment]
It's stupid AF

**Comment by Superfly-Inc** [comment]
Just messing around  but GitHub is less that intuitive - posting on a closed comment? W'Sup with that?
