### ISSUE TITLE
Checking Key Version using CLI

### ISSUE THREAD

**Issue by timmchugh11** [Superfly-Inc/ShowKeyPlus#47]
Hello,

I understand that you are no longer developing the CLI version of ShowKeyPlus, I am curious if the command line has an option to check a product key? Is this something you plan to expand on in the future?

To clarify, check a product key not installed on the machine ShowKeyPlus is running on.

Thanks

**Comment by Superfly-Inc** [comment]
Hi Timm

"Check.." was not part of the spec for CLI which was primarily developed for WinPE.. 

The current code base has changed significantly since the old versions so CLI will have to be re-coded from scratch for the current version... 

Can you give me a spec or use-case how it should be implemented?.. assume PE?

**Comment by timmchugh11** [comment]
I have a large number of keys in a database and I would like to automate checking what version of Windows they are for.

The keys are the OEM key from the machine BIOS and it will be used for auditing the machine and what OEM license it has.

**Comment by Wh1t3f0xy** [comment]
Hello Dears. I have faced with the same issue @timmchugh11 did you resolve that could you help me?
Thanks in advance!
